# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calendar.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='calendar.proto',
  package='calendar',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x63\x61lendar.proto\x12\x08\x63\x61lendar\x1a\x1fgoogle/protobuf/timestamp.proto\"E\n\x08\x43ustomer\x12\n\n\x02id\x18\x01 \x01(\x05\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x1a\n\x04Tail\x12\x12\n\ntailNumber\x18\x01 \x01(\t\"0\n\x10\x43ustomerTailList\x12\x1c\n\x04tail\x18\x01 \x03(\x0b\x32\x0e.calendar.Tailb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CUSTOMER = _descriptor.Descriptor(
  name='Customer',
  full_name='calendar.Customer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='calendar.Customer.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='calendar.Customer.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=130,
)


_TAIL = _descriptor.Descriptor(
  name='Tail',
  full_name='calendar.Tail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tailNumber', full_name='calendar.Tail.tailNumber', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=158,
)


_CUSTOMERTAILLIST = _descriptor.Descriptor(
  name='CustomerTailList',
  full_name='calendar.CustomerTailList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tail', full_name='calendar.CustomerTailList.tail', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=208,
)

_CUSTOMER.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_CUSTOMERTAILLIST.fields_by_name['tail'].message_type = _TAIL
DESCRIPTOR.message_types_by_name['Customer'] = _CUSTOMER
DESCRIPTOR.message_types_by_name['Tail'] = _TAIL
DESCRIPTOR.message_types_by_name['CustomerTailList'] = _CUSTOMERTAILLIST

Customer = _reflection.GeneratedProtocolMessageType('Customer', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMER,
  __module__ = 'calendar_pb2'
  # @@protoc_insertion_point(class_scope:calendar.Customer)
  ))
_sym_db.RegisterMessage(Customer)

Tail = _reflection.GeneratedProtocolMessageType('Tail', (_message.Message,), dict(
  DESCRIPTOR = _TAIL,
  __module__ = 'calendar_pb2'
  # @@protoc_insertion_point(class_scope:calendar.Tail)
  ))
_sym_db.RegisterMessage(Tail)

CustomerTailList = _reflection.GeneratedProtocolMessageType('CustomerTailList', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMERTAILLIST,
  __module__ = 'calendar_pb2'
  # @@protoc_insertion_point(class_scope:calendar.CustomerTailList)
  ))
_sym_db.RegisterMessage(CustomerTailList)


# @@protoc_insertion_point(module_scope)
